version: "3.1"

services:
  dailyreporter:
    container_name: dailyreporter
    build: /
    logging:
      options:
        max-size: "500m"
        max-file: "5"
    volumes:
      - daily-reporter-data:/app/data
    env_file: .env
    networks:
      - telegram-network

networks:
  telegram-network:
    driver: bridge

volumes:
  daily-reporter-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: "./dailyreporter"